# Generated by Django 3.1.5 on 2021-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastleMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('prefecture', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Castle',
        ),
    ]
