# Generated by Django 3.1.5 on 2021-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castles', '0002_auto_20210203_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castlemst',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
